### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by ali0408** [TheJoin95/500px-bot#3]
i'm new to python (in fact to computer coding in general). 

i'm running python 3.7.0b2 on macos X high sierra 10.13.3. 

even though I have already installed the requests module via pip, i keep getting this error message when I try to run the script:

File "init.py", line 4, in <module>
    import requests
ImportError: No module named requests

could you please help me with that? what am I doing wrong? thanks!

**Comment by ali0408** [comment]
@TheJoin95 I'd appreciate a lot if you could give me a hand. :)

**Comment by TheJoin95** [comment]
@ali0408 Hi, it looks like you did not install the requests module like it said.
Did you already check that you are using the right pip version for the python 3.7?

If you run pip install requests, it will install the module for the python version of pip, not for all the python version that you installed.

Let me know,
ty

**Comment by ali0408** [comment]
@TheJoin95 I reinstalled everything and also downloaded the repository files again, reconfigured login, pass, categories, tags, comments etc. 

I had some issues when I tried to RUN the script, when a popup appeared with this message:
Missing parentheses in call to 'print'. Did you mean print('init.py -u <email> -p <password> -c <config>')?

That happened for all the print commands. Although I'm really not familiar with the correct syntax, I tried to add the parenthesis on all of them as suggested on the popup. After thar I managed to proceed to the execution (with Python 3.7.), without that error message about the missing requests module.

But then I got another error message:
Traceback (most recent call last):
  File "/Users/ali/500px/init.py", line 9, in <module>
    from lib import utils
  File "/Users/ali/500px/lib/utils.py", line 27
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Do you have any idea about what am I doing wrong? :/

**Comment by TheJoin95** [comment]
Hi @ali0408 I made the project with a python 3.0 compatibility.
I need to review the code for python v > 3, also I need to improve some features so.. stay tuned :)

**Comment by noob83** [comment]
Hi @TheJoin95 I fixed whatever I could as I have 3.7 beta version of Python. Now I'm stuck with error 
 File "C:\Users\username\Downloads\500px-bot-master\500px-bot-master\lib\api\api.py", line 11, in <module>
    from search import search
ModuleNotFoundError: No module named 'search'

How do I install this module?

**Comment by jokassis** [comment]
@TheJoin95 i installed it and fixed a few errors basically parenthesis open and close missing after each print  request. However it is now stuck at   File "C:\Users\Jo\Desktop\500px-bot-master NEW\lib\utils.py", line 27
    except Exception, e: 
Any plan to work on it. looks like an amazing bot id it works. thank you.

**Comment by gdebre** [comment]
Hi guys the bot looks awesome but I know nothing about coding, can someone please send me the working version for python 3.7 ? that would be awesome
