### ISSUE TITLE
no such file or directory : 'backup/SEARCH', error "atexit._run" and "sys.exitfunc"

### ISSUE THREAD

**Issue by ghost** [TheJoin95/500px-bot#4]
Hi! It all works perfectly, but when it comes to end, this error appear.
How can I overcome this?

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/g4ryh0st/Desktop/500px-bot-master/init.py", line 59, in store_all_and_logout
    botClass.store_queue()
  File "/Users/g4ryh0st/Desktop/500px-bot-master/lib/bot/bot.py", line 202, in store_queue
    with open("backup/"+filename, mode='w') as backup:
IOError: [Errno 2] No such file or directory: 'backup/SEARCH'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/g4ryh0st/Desktop/500px-bot-master/init.py", line 59, in store_all_and_logout
    botClass.store_queue()
  File "/Users/g4ryh0st/Desktop/500px-bot-master/lib/bot/bot.py", line 202, in store_queue
    with open("backup/"+filename, mode='w') as backup:
IOError: [Errno 2] No such file or directory: 'backup/SEARCH'

**Comment by TheJoin95** [comment]
Thank you for submitting this issue.

The problem seems to be that the script don't have the permission to create the backup/SEARCH folder/file.

Can you please create that folder? So it can works without any problem,

let me know
thank you

**Comment by ghost** [comment]
(https://user-images.githubusercontent.com/48792586/54779741-38f4bc80-4c18-11e9-8c8c-2a902792b412.png)

I tried, but I obtain this:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/g4ryh0st/Desktop/500px-bot-master/init.py", line 59, in store_all_and_logout
    botClass.store_queue()
  File "/Users/g4ryh0st/Desktop/500px-bot-master/lib/bot/bot.py", line 202, in store_queue
    with open("backup/"+filename, mode='w') as backup:
IOError: [Errno 2] No such file or directory: 'backup/SEARCH'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/g4ryh0st/Desktop/500px-bot-master/init.py", line 59, in store_all_and_logout
    botClass.store_queue()
  File "/Users/g4ryh0st/Desktop/500px-bot-master/lib/bot/bot.py", line 202, in store_queue
    with open("backup/"+filename, mode='w') as backup:
IOError: [Errno 2] No such file or directory: 'backup/SEARCH'

**Comment by TheJoin95** [comment]
Ok, so can you please edit the file lib/bot/bot.py at this line:
`with open("backup/"+filename, mode='w')`

Change "backup/" to your full project path like "/Documents/Username/backup/".
Thank you

**Comment by ghost** [comment]
Ok now I got this:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/g4ryh0st/Desktop/500px-bot-master/init.py", line 59, in store_all_and_logout
    botClass.store_queue()
  File "/Users/g4ryh0st/Desktop/500px-bot-master/lib/bot/bot.py", line 203, in store_queue
    json.dump(self.constants[queueKey].queue, backup)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: deque([]) is not JSON serializable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/g4ryh0st/Desktop/500px-bot-master/init.py", line 59, in store_all_and_logout
    botClass.store_queue()
  File "/Users/g4ryh0st/Desktop/500px-bot-master/lib/bot/bot.py", line 203, in store_queue
    json.dump(self.constants[queueKey].queue, backup)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: deque([]) is not JSON serializable

**Comment by TheJoin95** [comment]
Ok, it seems correct now.
Of course if it is an empty list it will not work

**Comment by ghost** [comment]
Sorry, can you explain me which list? Ahaha
Btw thank you so much for your help!

**Comment by Hazard055** [comment]
Hey TheJoin95, fow how much money can you make me a full working 500px bot ? I need it for gaining followers, autolike and autocomment.

**Comment by Hazard055** [comment]
Maybe undetected ?
